### ISSUE TITLE
Errors in matchSurfaceLmksBD.m and Mesh/ExtractFeatures.m

### ISSUE THREAD

**Issue by bobbycho** [shaharkov/GPLmkBDMatch#1]
Hi,

When I run 'demo_GPLmkMatching.m', there is an error as follows:
Error using  + 
Matrix dimensions must agree.

Error in matchSurfaceLmksBD (line 72)
V = (isoParam{1}.V(1:2,:)' + T.t)*T.R';

And once running "demo_LmkMatching_versus_CPM.m", there is an erros as follows:
Error using  > 
Matrix dimensions must agree.

Error in Mesh/ExtractFeatures (line 36)
DNETruncInds = find(DNE > median(DNE));

Could you address me how to fix those errors?
Thanks,

**Comment by bobbycho** [comment]
I fixed the second error caused in ExtractFeatures (line 36) by modifying the line as follows:
DNETruncInds = find(DNE > repmat(median(DNE), size(DNE,1), 1));

Thanks

**Comment by shaharkov** [comment]
I'm guessing you use an older version of Matlab? Recent versions implicitly expand simple arithmetic to enable, for example, matrix-vector addition. One way around is to use bsxfun. 

Regardless, other problem could show up with older Matlab versions...

**Comment by bobbycho** [comment]
You are right! Once I followed your suggestions, everything works well!!
Thanks again.
